//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailsPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrailsPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trails Plugin.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delta {
            get {
                object obj = ResourceManager.GetObject("delta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropDown {
            get {
                object obj = ResourceManager.GetObject("DropDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighScore.
        /// </summary>
        internal static string HighScore_Trail {
            get {
                return ResourceManager.GetString("HighScore_Trail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A HighScore Trail can be generated..
        /// </summary>
        internal static string HighScoreCompatible {
            get {
                return ResourceManager.GetString("HighScoreCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighScore plugin.
        /// </summary>
        internal static string HighScorePluginName {
            get {
                return ResourceManager.GetString("HighScorePluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install at least version {0} of {1} to get a HighScore Trail..
        /// </summary>
        internal static string HighScoreToInstall {
            get {
                return ResourceManager.GetString("HighScoreToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem communicating with {0}.
        ///Make sure that {1} is installed..
        /// </summary>
        internal static string OtherPluginExceptionText {
            get {
                return ResourceManager.GetString("OtherPluginExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected version {0} of {1}..
        /// </summary>
        internal static string OtherPluginVersion {
            get {
                return ResourceManager.GetString("OtherPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Name At Import.
        /// </summary>
        internal static string SetNameAtImport {
            get {
                return ResourceManager.GetString("SetNameAtImport", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap square_blue {
            get {
                object obj = ResourceManager.GetObject("square_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap square_green {
            get {
                object obj = ResourceManager.GetObject("square_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap square_green_check {
            get {
                object obj = ResourceManager.GetObject("square_green_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap square_green_minus {
            get {
                object obj = ResourceManager.GetObject("square_green_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap square_green_plus {
            get {
                object obj = ResourceManager.GetObject("square_green_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap square_red {
            get {
                object obj = ResourceManager.GetObject("square_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap square_red_plus {
            get {
                object obj = ResourceManager.GetObject("square_red_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Trail in List --.
        /// </summary>
        internal static string Trail_NoTrailSelected {
            get {
                return ResourceManager.GetString("Trail_NoTrailSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Activity.
        /// </summary>
        internal static string Trail_Reference_Name {
            get {
                return ResourceManager.GetString("Trail_Reference_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail Charts.
        /// </summary>
        internal static string TrailChartsName {
            get {
                return ResourceManager.GetString("TrailChartsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail.
        /// </summary>
        internal static string TrailName {
            get {
                return ResourceManager.GetString("TrailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail Points.
        /// </summary>
        internal static string TrailPointsControlLayer {
            get {
                return ResourceManager.GetString("TrailPointsControlLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trails.
        /// </summary>
        internal static string TrailsName {
            get {
                return ResourceManager.GetString("TrailsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trail.
        /// </summary>
        internal static string UI_Activity_EditTrail_AddTrail {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_AddTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a copy of the Trail?.
        /// </summary>
        internal static string UI_Activity_EditTrail_Copy {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click the table to edit values..
        /// </summary>
        internal static string UI_Activity_EditTrail_EditRow {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_EditRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trail.
        /// </summary>
        internal static string UI_Activity_EditTrail_EditTrail {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_EditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Trail as activity?.
        /// </summary>
        internal static string UI_Activity_EditTrail_Export {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert failed.
        /// </summary>
        internal static string UI_Activity_EditTrail_InsertFailed {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string UI_Activity_EditTrail_Latitude {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string UI_Activity_EditTrail_Longitude {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        internal static string UI_Activity_EditTrail_Radius {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius must be numeric..
        /// </summary>
        internal static string UI_Activity_EditTrail_RadiusNumeric {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_RadiusNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail name is required..
        /// </summary>
        internal static string UI_Activity_EditTrail_TrailNameReqiured {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_TrailNameReqiured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique trail name is required..
        /// </summary>
        internal static string UI_Activity_EditTrail_UniqueTrailNameRequired {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_UniqueTrailNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        internal static string UI_Activity_EditTrail_UpdateFailed {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add InBound activities as results.
        /// </summary>
        internal static string UI_Activity_List_AddInBound {
            get {
                return ResourceManager.GetString("UI_Activity_List_AddInBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string UI_Activity_List_Advanced {
            get {
                return ResourceManager.GetString("UI_Activity_List_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude result from list.
        /// </summary>
        internal static string UI_Activity_List_ExcludeResult {
            get {
                return ResourceManager.GetString("UI_Activity_List_ExcludeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit activities to activities selected in list.
        /// </summary>
        internal static string UI_Activity_List_LimitSelection {
            get {
                return ResourceManager.GetString("UI_Activity_List_LimitSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Settings....
        /// </summary>
        internal static string UI_Activity_List_ListSettings {
            get {
                return ResourceManager.GetString("UI_Activity_List_ListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Reference result ({0}, Current: {1}).
        /// </summary>
        internal static string UI_Activity_List_ReferenceResult {
            get {
                return ResourceManager.GetString("UI_Activity_List_ReferenceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark other sub Trails or splits in list.
        /// </summary>
        internal static string UI_Activity_List_Splits {
            get {
                return ResourceManager.GetString("UI_Activity_List_Splits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Unique Routes Common Stretches.
        /// </summary>
        internal static string UI_Activity_List_URCommon {
            get {
                return ResourceManager.GetString("UI_Activity_List_URCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit activities with Unique Routes from reference result{0}.
        /// </summary>
        internal static string UI_Activity_List_URLimit {
            get {
                return ResourceManager.GetString("UI_Activity_List_URLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add similar activities with Unique Routes from reference result{0}.
        /// </summary>
        internal static string UI_Activity_List_URSelect {
            get {
                return ResourceManager.GetString("UI_Activity_List_URSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Chart Tools.
        /// </summary>
        internal static string UI_Activity_Menu_HideToolBar {
            get {
                return ResourceManager.GetString("UI_Activity_Menu_HideToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Chart Tools.
        /// </summary>
        internal static string UI_Activity_Menu_ShowToolBar {
            get {
                return ResourceManager.GetString("UI_Activity_Menu_ShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No point selected on the map.
        ///
        ///Press {0} to use the Lap points, {1} to abort and select points on the GPS track..
        /// </summary>
        internal static string UI_Activity_Page_AddTrail_NoSelected {
            get {
                return ResourceManager.GetString("UI_Activity_Page_AddTrail_NoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to add the selected points to current trail, {1} to add a new trail..
        /// </summary>
        internal static string UI_Activity_Page_AddTrail_Replace {
            get {
                return ResourceManager.GetString("UI_Activity_Page_AddTrail_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new trail or selected points to current trail. (Select points on the map before pushing this button)..
        /// </summary>
        internal static string UI_Activity_Page_AddTrail_TT {
            get {
                return ResourceManager.GetString("UI_Activity_Page_AddTrail_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this trail..
        /// </summary>
        internal static string UI_Activity_Page_DeleteTrail_TT {
            get {
                return ResourceManager.GetString("UI_Activity_Page_DeleteTrail_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this trail?.
        /// </summary>
        internal static string UI_Activity_Page_DeleteTrailConfirm {
            get {
                return ResourceManager.GetString("UI_Activity_Page_DeleteTrailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this trail. (Select the trail points on the map before pushing this button)..
        /// </summary>
        internal static string UI_Activity_Page_EditTrail_TT {
            get {
                return ResourceManager.GetString("UI_Activity_Page_EditTrail_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a point on the map.
        ///
        ///To select a point, just click on the track.
        ///Add new points by pressing the Add button.
        ///
        ///To make a copy of the current reference activity, select Trail {0}, then press Edit button..
        /// </summary>
        internal static string UI_Activity_Page_SelectPointsError {
            get {
                return ResourceManager.GetString("UI_Activity_Page_SelectPointsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a point on the map.
        ///
        ///To select a point, just click on the track.
        ///Add new points by pressing the Add button.
        ///
        ///To select a second point, hold down CTRL, and click another part of the track.
        ///Select as many points required to make this trail unique from other trails.
        ///
        ///To make a copy of the current reference activity, select Trail {0}, then press Edit button..
        /// </summary>
        internal static string UI_Activity_Page_SelectPointsError_ST2 {
            get {
                return ResourceManager.GetString("UI_Activity_Page_SelectPointsError_ST2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the trail GPS locations
        ///to currently selected points?.
        /// </summary>
        internal static string UI_Activity_Page_UpdateTrail {
            get {
                return ResourceManager.GetString("UI_Activity_Page_UpdateTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Resync Diff at Trail Points.
        /// </summary>
        internal static string UI_Chart_adjustResyncDiffAtTrailPoints {
            get {
                return ResourceManager.GetString("UI_Chart_adjustResyncDiffAtTrailPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resync Diff at Trail Points.
        /// </summary>
        internal static string UI_Chart_resyncDiffAtTrailPoints {
            get {
                return ResourceManager.GetString("UI_Chart_resyncDiffAtTrailPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Chart at Trail Points.
        /// </summary>
        internal static string UI_Chart_syncChartAtTrailPoints {
            get {
                return ResourceManager.GetString("UI_Chart_syncChartAtTrailPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Radius.
        /// </summary>
        internal static string UI_Settings_DefaultRadius {
            get {
                return ResourceManager.GetString("UI_Settings_DefaultRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default radius for trail points when adding new trails.
        ///Changing this value will not effect existing trails..
        /// </summary>
        internal static string UI_Settings_DefaultRadius_ToolTip {
            get {
                return ResourceManager.GetString("UI_Settings_DefaultRadius_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities can be filtered using Unique Routes..
        /// </summary>
        internal static string UniqueRoutesCompatible {
            get {
                return ResourceManager.GetString("UniqueRoutesCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Routes plugin.
        /// </summary>
        internal static string UniqueRoutesPluginName {
            get {
                return ResourceManager.GetString("UniqueRoutesPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install at least version {0} of {1} to filter activities using Unique Routes..
        /// </summary>
        internal static string UniqueRoutesToInstall {
            get {
                return ResourceManager.GetString("UniqueRoutesToInstall", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ZoomToContent {
            get {
                object obj = ResourceManager.GetObject("ZoomToContent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
