//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailsPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrailsPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap square_blue {
            get {
                object obj = ResourceManager.GetObject("square_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap square_green {
            get {
                object obj = ResourceManager.GetObject("square_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap square_red {
            get {
                object obj = ResourceManager.GetObject("square_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trails.
        /// </summary>
        internal static string TrailsName {
            get {
                return ResourceManager.GetString("TrailsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trails Plugin.
        /// </summary>
        internal static string TrailsPluginName {
            get {
                return ResourceManager.GetString("TrailsPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail.
        /// </summary>
        internal static string UI_Action_Title {
            get {
                return ResourceManager.GetString("UI_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trail.
        /// </summary>
        internal static string UI_Activity_EditTrail_AddTrail {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_AddTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trail.
        /// </summary>
        internal static string UI_Activity_EditTrail_EditTrail {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_EditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert failed.
        /// </summary>
        internal static string UI_Activity_EditTrail_InsertFailed {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string UI_Activity_EditTrail_Latitude {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string UI_Activity_EditTrail_Longitude {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        internal static string UI_Activity_EditTrail_Radius {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius must be numeric..
        /// </summary>
        internal static string UI_Activity_EditTrail_RadiusNumeric {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_RadiusNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail name is required..
        /// </summary>
        internal static string UI_Activity_EditTrail_TrailNameReqiured {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_TrailNameReqiured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique trail name is required..
        /// </summary>
        internal static string UI_Activity_EditTrail_UniqueTrailNameRequired {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_UniqueTrailNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        internal static string UI_Activity_EditTrail_UpdateFailed {
            get {
                return ResourceManager.GetString("UI_Activity_EditTrail_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new trail. (Select the trail points on the map before pushing this button)..
        /// </summary>
        internal static string UI_Activity_Page_AddTrail_TT {
            get {
                return ResourceManager.GetString("UI_Activity_Page_AddTrail_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this trail..
        /// </summary>
        internal static string UI_Activity_Page_DeleteTrail_TT {
            get {
                return ResourceManager.GetString("UI_Activity_Page_DeleteTrail_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this trail?.
        /// </summary>
        internal static string UI_Activity_Page_DeleteTrailConfirm {
            get {
                return ResourceManager.GetString("UI_Activity_Page_DeleteTrailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this trail. (Select the trail points on the map before pushing this button)..
        /// </summary>
        internal static string UI_Activity_Page_EditTrail_TT {
            get {
                return ResourceManager.GetString("UI_Activity_Page_EditTrail_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Settings....
        /// </summary>
        internal static string UI_Activity_Page_ListSettings {
            get {
                return ResourceManager.GetString("UI_Activity_Page_ListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least two points on the map ({0} now selected).
        ///
        ///To select a point, just click on a track that you have ridden.
        ///To select a second point, hold down CTRL, and click another part of the track.
        ///Select as many points required to make this trail unique from other trails.
        ///.
        /// </summary>
        internal static string UI_Activity_Page_SelectPointsError {
            get {
                return ResourceManager.GetString("UI_Activity_Page_SelectPointsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the trail GPS locations
        ///to currently selected points?.
        /// </summary>
        internal static string UI_Activity_Page_UpdateTrail {
            get {
                return ResourceManager.GetString("UI_Activity_Page_UpdateTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Radius.
        /// </summary>
        internal static string UI_Settings_DefaultRadius {
            get {
                return ResourceManager.GetString("UI_Settings_DefaultRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default radius for trail points when adding new trails.
        ///Changing this value will not effect existing trails..
        /// </summary>
        internal static string UI_Settings_DefaultRadius_ToolTip {
            get {
                return ResourceManager.GetString("UI_Settings_DefaultRadius_ToolTip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ZoomToContent {
            get {
                object obj = ResourceManager.GetObject("ZoomToContent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
